import React from 'react';
import { AnalysisResponse, Severity, IssueType } from '../types';
import { AlertTriangle, AlertOctagon, Info, CheckCircle2, FileSearch } from 'lucide-react';

interface AnalysisResultsProps {
  data: AnalysisResponse | null;
  loading: boolean;
}

const SeverityBadge: React.FC<{ severity: Severity }> = ({ severity }) => {
  switch (severity) {
    case Severity.CRITICAL:
      return (
        <span className="inline-flex items-center px-2.5 py-1 rounded-md text-xs font-semibold bg-red-50 text-red-700 border border-red-100">
          <AlertOctagon className="w-3 h-3 mr-1.5" />
          Critical Risk
        </span>
      );
    case Severity.MODERATE:
      return (
        <span className="inline-flex items-center px-2.5 py-1 rounded-md text-xs font-semibold bg-amber-50 text-amber-700 border border-amber-100">
          <AlertTriangle className="w-3 h-3 mr-1.5" />
          Moderate Risk
        </span>
      );
    case Severity.LOW:
      return (
        <span className="inline-flex items-center px-2.5 py-1 rounded-md text-xs font-semibold bg-zinc-100 text-zinc-700 border border-zinc-200">
          <Info className="w-3 h-3 mr-1.5" />
          Low Risk
        </span>
      );
    default:
      return null;
  }
};

const TypeBadge: React.FC<{ type: IssueType }> = ({ type }) => {
    return (
        <span className="text-[10px] uppercase tracking-widest font-bold text-zinc-500">
            {type}
        </span>
    )
}

const AnalysisResults: React.FC<AnalysisResultsProps> = ({ data, loading }) => {
  if (loading) {
    return (
      <div className="w-full py-20 flex flex-col items-center justify-center text-center animate-pulse">
        <div className="relative mb-8">
            <div className="h-20 w-20 rounded-full border-[3px] border-zinc-100 border-t-zinc-900 animate-spin"></div>
            <div className="absolute inset-0 flex items-center justify-center">
                <FileSearch className="h-8 w-8 text-zinc-900" />
            </div>
        </div>
        <h3 className="text-xl font-semibold text-zinc-900">Analyzing Documents</h3>
        <p className="text-zinc-500 mt-2 max-w-sm">Knot is reading your contracts and cross-referencing clauses...</p>
      </div>
    );
  }

  if (!data) return null;

  const criticalCount = data.issues.filter(i => i.severity === Severity.CRITICAL).length;
  const moderateCount = data.issues.filter(i => i.severity === Severity.MODERATE).length;

  return (
    <div className="space-y-10 animate-fade-in-up pb-20">
      <div className="bg-white rounded-2xl shadow-sm border border-zinc-200 p-8">
        <div className="flex flex-col md:flex-row md:items-start md:justify-between mb-6 gap-4">
            <div>
                <h2 className="text-2xl font-bold text-zinc-900">Analysis Summary</h2>
                <p className="text-zinc-500 text-sm mt-1">Generated by Knot AI Engine</p>
            </div>
            <div className="flex gap-3">
                <div className={`flex flex-col items-center px-5 py-2 rounded-xl border ${criticalCount > 0 ? 'bg-red-50 border-red-100' : 'bg-zinc-50 border-zinc-100 opacity-50'}`}>
                    <span className={`text-2xl font-bold ${criticalCount > 0 ? 'text-red-600' : 'text-zinc-400'}`}>{criticalCount}</span>
                    <span className={`text-[10px] font-bold uppercase tracking-wider ${criticalCount > 0 ? 'text-red-800' : 'text-zinc-400'}`}>Critical</span>
                </div>
                 <div className={`flex flex-col items-center px-5 py-2 rounded-xl border ${moderateCount > 0 ? 'bg-amber-50 border-amber-100' : 'bg-zinc-50 border-zinc-100 opacity-50'}`}>
                    <span className={`text-2xl font-bold ${moderateCount > 0 ? 'text-amber-600' : 'text-zinc-400'}`}>{moderateCount}</span>
                    <span className={`text-[10px] font-bold uppercase tracking-wider ${moderateCount > 0 ? 'text-amber-800' : 'text-zinc-400'}`}>Moderate</span>
                 </div>
            </div>
        </div>
        <div className="text-zinc-700 leading-relaxed bg-zinc-50/50 p-6 rounded-xl border border-zinc-100/50">
          <p>{data.summary}</p>
        </div>
      </div>

      <div>
        <div className="flex items-center justify-between mb-6">
            <h3 className="text-xl font-bold text-zinc-900">Detected Issues</h3>
            <span className="text-sm font-medium text-zinc-500 bg-white border border-zinc-200 px-3 py-1 rounded-full shadow-sm">
                {data.issues.length} Issues Found
            </span>
        </div>
        
        <div className="space-y-6">
          {data.issues.map((issue) => (
            <div 
              key={issue.id} 
              className="bg-white rounded-2xl border border-zinc-200 shadow-sm p-6 md:p-8 transition-all hover:shadow-md hover:border-zinc-300"
            >
              <div className="flex flex-col md:flex-row md:items-start justify-between gap-4 mb-4">
                <div className="flex-1">
                  <div className="flex items-center gap-3 mb-3">
                    <SeverityBadge severity={issue.severity} />
                    <span className="text-zinc-300">|</span>
                    <TypeBadge type={issue.type} />
                  </div>
                  <h4 className="text-xl font-semibold text-zinc-900 mb-2">{issue.title}</h4>
                  <p className="text-zinc-600 leading-relaxed">{issue.description}</p>
                </div>
              </div>

              {(issue.sourceDoc1 || issue.sourceDoc2) && (
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-6 bg-zinc-50/80 p-6 rounded-xl border border-zinc-100">
                    {issue.sourceDoc1 && (
                        <div className="relative">
                            <span className="text-[10px] font-bold text-zinc-400 uppercase tracking-widest mb-2 block">Document A Reference</span>
                            <blockquote className="text-sm text-zinc-600 pl-4 border-l-2 border-zinc-300 italic relative">
                                "{issue.sourceDoc1}"
                            </blockquote>
                        </div>
                    )}
                    {issue.sourceDoc2 && (
                        <div className="relative">
                            <span className="text-[10px] font-bold text-red-400 uppercase tracking-widest mb-2 block">Conflicting Clause</span>
                            <blockquote className="text-sm text-zinc-700 pl-4 border-l-2 border-red-300 italic bg-red-50/30 py-1 -mr-2 pr-2 rounded-r">
                                "{issue.sourceDoc2}"
                            </blockquote>
                        </div>
                    )}
                  </div>
              )}

              <div className="mt-6 flex flex-col sm:flex-row sm:items-center justify-between text-sm pt-6 border-t border-zinc-100">
                <div className="text-zinc-500 mb-2 sm:mb-0 font-mono text-xs">
                    REF: {issue.pageRef || 'N/A'}
                </div>
                {issue.recommendation && (
                    <div className="flex items-start text-emerald-700 bg-emerald-50 px-4 py-2 rounded-lg border border-emerald-100/50 max-w-lg">
                        <CheckCircle2 className="w-4 h-4 mr-2 mt-0.5 flex-shrink-0" />
                        <span className="font-medium">{issue.recommendation}</span>
                    </div>
                )}
              </div>
            </div>
          ))}
          
          {data.issues.length === 0 && (
            <div className="flex flex-col items-center justify-center py-16 bg-white rounded-2xl border border-dashed border-zinc-300">
                <div className="bg-emerald-50 p-4 rounded-full mb-4">
                    <CheckCircle2 className="h-8 w-8 text-emerald-500" />
                </div>
                <h3 className="text-lg font-bold text-zinc-900">Clean Analysis</h3>
                <p className="text-zinc-500 mt-1">Knot detected no contradictions or major risks.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default AnalysisResults;